pipeline:
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: orglevelmission5connector
        build: <+input>
  stages:
    - stage:
        name: Do maven install
        identifier: Do_maven_install
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: package step
                  identifier: package_step
                  spec:
                    connectorRef: dockerhubpat
                    image: maven:amazoncorretto
                    shell: Sh
                    command: mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
              - step:
                  type: Run
                  name: list filenames
                  identifier: list_filenames
                  spec:
                    shell: Sh
                    command: |-
                      echo "HELLO"
                      pwd
                      ls target -l
                      cp ./target/hello-world-1.0.jar myjar.jar
                      ls target -l
              - step:
                  type: Run
                  name: curl to nexus
                  identifier: curl_ti_nexus
                  spec:
                    shell: Sh
                    command: |-
                      echo "CURL"
                      curl -v -u nexus-connector-user:2025NexusHarness -F "maven2.generate-pom=false" -F "maven2.asset1=@./target/pom.xml" -F "maven2.asset1.extension=pom" -F "maven2.asset2=@./target/hello-world-1.0.jar;type=application/java-archive" -F "maven2.asset2.extension=jar" "http://http://35.210.166.33:8081/service/rest/v1/components?repository=maven-releases"
                      echo "END CURL"
          sharedPaths:
            - /root/.m2
            - /shared/myfolder
          buildIntelligence:
            enabled: false
        variables:
          - name: nexus_repo
            type: String
            description: ""
            required: false
            value: maven-public
          - name: nexus_url
            type: String
            description: ""
            required: false
            value: http://35.210.166.33:8081/
  identifier: Mission5_Manual_Nexus_Push
  name: Mission5 - Manual Nexus Push
