pipeline:
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: orglevelmission5connector
        build: <+input>
  stages:
    - stage:
        name: Do maven install
        identifier: Do_maven_install
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: install step
                  identifier: install_step
                  spec:
                    connectorRef: dockerhubpat
                    image: maven:amazoncorretto
                    shell: Sh
                    command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
              - step:
                  type: Run
                  name: docker step push to nexus
                  identifier: docker_step_push_to_nexus
                  spec:
                    shell: Sh
                    command: docker run --rm -e PLUGIN_USERNAME=nexus-connector-user -e PLUGIN_PASSWORD=2025NexusHarness -e PLUGIN_SERVER_URL=http://35.210.166.33:8081/ -e PLUGIN_FILENAME=./target/hello-world-maven-1.0-SNAPSHOT.jar -e PLUGIN_FORMAT=maven2 -e PLUGIN_REPOSITORY=maven-snapshots -e PLUGIN_ATTRIBUTES="-CgroupId=com.qa -CartifactId=hello-world-example -Cversion=1.0 -Aextension=jar -Aclassifier=bin" harnesscommunity/publish-nexus-repository:1.1.1
                    privileged: true
                    envVariables:
                      PLUGIN_USERNAME: <+stage.variables.nexus_user>
        variables:
          - name: nexus_repo
            type: String
            description: ""
            required: false
            value: maven-public
          - name: nexus_url
            type: String
            description: ""
            required: false
            value: http://35.210.166.33:8081/
  identifier: Mission5_Manual_Nexus_Push
  name: Mission5 - Manual Nexus Push
